export default {
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
  UPDATE_APP_DATA: 'UPDATE_APP_DATA',
  CLEAR_APP_DATA: 'CLEAR_APP_DATA',
  IS_APP_LOADING: 'IS_APP_LOADING',
  UPDATE_PAGE_DATA: 'UPDATE_PAGE_DATA',
  UPDATE_FORM_DATA: 'UPDATE_FORM_DATA',
  CLEAR_PAGE_DATA: 'CLEAR_PAGE_DATA',
  SEND_FORM_DATA: 'SEND_FORM_DATA',
  IS_PAGE_LOADING: 'IS_PAGE_LOADING',
  SET_PAGE_ERROR: 'SET_PAGE_ERROR',
  SET_APP_ERROR: 'SET_APP_ERROR'
};